version: "3.8"

services:
  # API
  smart-brain-api:
    container_name: api
    build: .
    ports: 
      - "3000:3000"
    environment:
      POSTGRES_USER: thangphan-docker
      POSTGRES_DB: smart-brain-docker
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST: postgres
    volumes:
      - "./:/usr/src/smart-brain-api"
  #Database
  postgres:
    container_name: db
    image: postgres
    build: ./postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: thangphan-docker
      POSTGRES_DB: smart-brain-docker
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST: postgres
